controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api:
    resource: .
    type: api_platform
api_login_user:
    path: /api/login-user
    controller: App\Controller\LoginController::login
    methods: POST